use customasm::*;


// generated by build script
include!(concat!(env!("OUT_DIR"), "/std_files.rs"));


fn main()
{
	let args: Vec<String> = std::env::args().collect();
	
	let mut fileserver = util::FileServerReal::new();
	fileserver.add_std_files(STD_FILES);
	
	if let Err(()) = driver::drive(&args, &mut fileserver)
	{
		std::process::exit(1);
	}
}