use customasm::*;


// generated by build script
include!(concat!(env!("OUT_DIR"), "/std_files.rs"));


pub mod driver;


fn main()
{
	let args: Vec<String> = std::env::args().collect();
	
	let mut fileserver = util::FileServerReal::new();
	fileserver.add_std_files(STD_FILES);
	
	let maybe_result = driver::drive_from_commandline(
		&args,
		&mut fileserver);

	if let Err(()) = maybe_result
	{
		std::process::exit(1);
	}
}